#!/usr/bin/env node

//Get argument values
var 	op 	 =	 process.argv[2], 	//The operator for the math
		x	 = +(process.argv[3]), 	//The first variable
		y	 = +(process.argv[4]); 	//The second variable
		math = require('./math'); 	//Import math module

console.log(math[op](x, y));